# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - rust-gameboy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install and build
      run: |
        npm install -g serve
        npm install
        npm run build --if-present

    - name: 'Get list of files'
      run: ls -a

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rust-gameboy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e285611aba4847fdadf1d9f91c1f45a8 }}
        package: '$(System.DefaultWorkingDirectory)/build'